// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function CleanProxy():Promise<number>;

export function DeleteRule(arg1:database.Rules):Promise<number>;

export function GetRuleList():Promise<Array<database.Rules>>;

export function GetRules():Promise<Array<string>>;

export function SaveRules(arg1:main.CurrentRule):Promise<number>;

export function StartProxy(arg1:string,arg2:string):Promise<number>;
