// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanProxy() {
  return window['go']['main']['App']['CleanProxy']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetRuleList() {
  return window['go']['main']['App']['GetRuleList']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function SaveRules(arg1) {
  return window['go']['main']['App']['SaveRules'](arg1);
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}
